Models/EditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentsCRUDWithImageMVC.Models
{
    public class EditModel
    {
        public int RollNo { get; set; }
        public String Name { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public int Fees { get; set; }
        public DateTime JoiningDate { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public byte[] Image { get; set; }

    }
}

Models/GetDetailsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentsCRUDWithImageMVC.Models
{
    public class GetDetailsModel
    {
        public String Name { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public int Fees { get; set; }
        public DateTime JoiningDate { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public byte[] Image { get; set; }
    }
}

Models/InsertModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentsCRUDWithImageMVC.Models
{
    public class InsertModel
    {
        public String Name { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public int Fees { get; set; }
        public DateTime JoiningDate { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public byte[] Image { get; set; }

    }
}

Models/ListsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentsCRUDWithImageMVC.Models
{
    public class ListsModel
    {
        public int RollNo { get; set; }
        public String Name { get; set; }
        public String City { get; set; }
        public String State { get; set; }
        public int Fees { get; set; }
        public DateTime JoiningDate { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public byte[] Image { get; set; }  

    }
}

Models/MessageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StudentsCRUDWithImageMVC.Models
{
    public class MessageModel
    {
        public int MessageId { get; set; }
        public string SenderEmail { get; set; }
        public string ReceiverEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public DateTime SentDate { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentsCRUDWithImageMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/StudentsController.cs
using StudentsCRUDWithImageMVC.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace StudentsCRUDWithImageMVC.Controllers
{
    public class StudentsController : Controller
    {
        Logic _logic = new Logic();
        // GET:                            Lists Of Students
        [HttpGet]
        public ActionResult Lists()
        {
            return View(_logic.GetAllStudentsDetails());
        }

        // GET:                     GetDetails     Students/Details/5
        [HttpGet]
        public ActionResult Details(int id)
        {
            var details = _logic.GetAllStudentsDetails().Find(de => de.RollNo == id);
            return View(details);
        }

        // GET: Students/Create
        [HttpGet]
        public ActionResult Insert()
        {
            return View();
        }
        //------------------------------------------------
        private string ToTitleCase(string input)
        {
            if (string.IsNullOrWhiteSpace(input)) return input;

            System.Globalization.CultureInfo cultureInfo = System.Threading.Thread.CurrentThread.CurrentCulture;
            System.Globalization.TextInfo textInfo = cultureInfo.TextInfo;
            return textInfo.ToTitleCase(input.ToLower());
        }
        //------------------------------------------


        // POST: Students/Create
        [HttpPost]
        public ActionResult Insert(InsertModel insertStdValues)
        {
            try
            {
                if (insertStdValues.ImageFile != null && insertStdValues.ImageFile.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(insertStdValues.ImageFile.InputStream))
                    {
                        insertStdValues.Image = binaryReader.ReadBytes(insertStdValues.ImageFile.ContentLength);
                    }
                }
                // Capitalize each word before saving
                insertStdValues.Name = ToTitleCase(insertStdValues.Name);
                insertStdValues.City = ToTitleCase(insertStdValues.City);
                insertStdValues.State = ToTitleCase(insertStdValues.State);

                _logic.insertDetails(insertStdValues); // Save data

                return RedirectToAction("Lists"); // Redirect to Lists after save
            }
            catch
            {
                return View();
            }
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int id)
        {
            var students = _logic.GetAllStudentsDetails().Find(s => s.RollNo == id);
            return View(students);
        }

        // POST: Students/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EditModel EditStdValues)
        {
            try
            {
                if (EditStdValues.ImageFile != null && EditStdValues.ImageFile.ContentLength > 0)
                {
                    using (var binaryReader = new BinaryReader(EditStdValues.ImageFile.InputStream))
                    {
                        EditStdValues.Image = binaryReader.ReadBytes(EditStdValues.ImageFile.ContentLength);
                    }
                }
                EditStdValues.Name = ToTitleCase(EditStdValues.Name);
                EditStdValues.City = ToTitleCase(EditStdValues.City);
                EditStdValues.State = ToTitleCase(EditStdValues.State);

                // TODO: Add update logic here
                _logic.EditDetails(EditStdValues);

                return RedirectToAction("Lists");
            }
            catch
            {
                return View(EditStdValues);
            }
            
        }

        //GET: Students/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var del = _logic.GetAllStudentsDetails().Find(de => de.RollNo == id);
            return View(del);
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            _logic.DeleteDetails(id);
            return RedirectToAction("Lists");
        }

        [HttpGet]
        public ActionResult Compose()
        {
            return View();
        }

        // Handle sending message
        [HttpPost]
        public ActionResult Compose(MessageModel messageModel)
        {
            if (ModelState.IsValid)
            {
                _logic.InsertMessage(messageModel);
                return RedirectToAction("SentItems", new { email = messageModel.SenderEmail });
            }
            return View(messageModel);
        }

        // Inbox
        public ActionResult Inbox(string email)
        {
            if (string.IsNullOrEmpty(email))
                return View(new List<MessageModel>());

            var messages = _logic.GetInboxMessages(email);
            return View(messages);
        }

        // Sent Items
        public ActionResult SentItems(string email)
        {
            if (string.IsNullOrEmpty(email))
                return View(new List<MessageModel>());

            var messages = _logic.GetSentMessages(email);
            return View(messages);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <!-- ✅ Use StudentsController since your G-Clone is in it -->
                    <li>@Html.ActionLink("Compose", "Compose", "Students", null, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Inbox", "Inbox", "Students", new { email = "student@email.com" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sent", "SentItems", "Students", new { email = "student@email.com" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Students/Compose.cshtml
@model StudentsCRUDWithImageMVC.Models.MessageModel

<h2>Compose Message</h2>

@using (Html.BeginForm())
{
    <div>
        <label>Sender Email:</label>
        @Html.TextBoxFor(m => m.SenderEmail)
    </div>
    <div>
        <label>Receiver Email:</label>
        @Html.TextBoxFor(m => m.ReceiverEmail)
    </div>
    <div>
        <label>Subject:</label>
        @Html.TextBoxFor(m => m.Subject)
    </div>
    <div>
        <label>Body:</label>
        @Html.TextAreaFor(m => m.Body)
    </div>
    <input type="submit" value="Send" />
}

Views/Students/Delete.cshtml
@model StudentsCRUDWithImageMVC.Models.ListsModel

@{
    ViewBag.Title = "Delete";
}


<h3 style="color:red" align="center">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RollNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RollNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fees)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fees)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JoiningDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JoiningDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @if (Model.Image != null)
            {
                string imageBase64 = Convert.ToBase64String(Model.Image);
                string imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                <img src="@imageSrc" width="100" height="100" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> &nbsp; 
    @Html.ActionLink("Back to List", "Lists", null, new { @class = "btn btn-primary", style = "margin-left:10px;" })
</div>   
    }
</div>

Views/Students/Details.cshtml
@model StudentsCRUDWithImageMVC.Models.ListsModel

@{
    ViewBag.Title = "Details";
}

<h2 style="color:crimson" align="center">Student Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>Roll No</dt>
        <dd>@Model.RollNo</dd>

        <dt>Name</dt>
        <dd>@Model.Name</dd>

        <dt>City</dt>
        <dd>@Model.City</dd>

        <dt>State</dt>
        <dd>@Model.State</dd>

        <dt>Fees</dt>
        <dd>@Model.Fees</dd>

        <dt>Joining Date</dt>
        <dd>@Model.JoiningDate.ToShortDateString()</dd>

        <dt>Photo</dt>
        <dd>
            @if (Model.Image != null)
            {
                var base64 = Convert.ToBase64String(Model.Image);
                var imgSrc = $"data:image/jpg;base64,{base64}";
                <img src="@imgSrc" width="100" height="100" />
            }
            else
            {
                <span>No Image</span>
            }
            @Html.ActionLink("Back to List", "Lists", null, new { @class = "btn btn-primary", style = "margin-left:10px;" })
        </dd>

    </dl>
</div>

<p>
    
</p>

Views/Students/Edit.cshtml
@model StudentsCRUDWithImageMVC.Models.ListsModel


@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm("Edit", "Students", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color:maroon" align="center">You Need Some Edits</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RollNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RollNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RollNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        @*<div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>*@
        <div class="form-group">
            <label>Upload New Image (optional)</label>
            <input type="file" name="ImageFile" class="form-control" />
        </div>
        <br />
        @if (Model.Image != null)
        {
            string imageBase64 = Convert.ToBase64String(Model.Image);
            string imageSrc = $"data:image/jpg;base64,{imageBase64}";
            <img src="@imageSrc" width="100" height="80" />
        }
        &nbsp; &nbsp; &nbsp;
        <input type="submit" value="Update" class="btn btn-success" />
        @Html.ActionLink("Back to List", "Lists", null, new { @class = "btn btn-secondary", style = "margin-left:10px;" })

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Students/Inbox.cshtml
@model List<StudentsCRUDWithImageMVC.Models.MessageModel>

<h2>Inbox</h2>

<table>
    <thead>
        <tr>
            <th>From</th>
            <th>Subject</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var msg in Model)
        {
            <tr>
                <td>@msg.SenderEmail</td>
                <td>@msg.Subject</td>
                <td>@msg.SentDate.ToString("g")</td>
            </tr>
        }
    </tbody>
</table>

Views/Students/Insert.cshtml
@model StudentsCRUDWithImageMVC.Models.InsertModel

@{
    ViewBag.Title = "Insert";
}



@using (Html.BeginForm("Insert", "Students", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color: blueviolet" align="center">Insert New Member Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fees, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fees, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fees, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

    </div>

    <!-- Image Upload field -->
    <div class="form-group">
        @Html.Label("Upload Image", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" id="ImageFile" class="form-control" />
        </div>
    </div>
    <br />
    <!-- Submit button -->
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-success" />
        @Html.ActionLink("Back to List", "Lists", null, new { @class = "btn btn-secondary", style = "margin-left:10px;" })
    </div>


}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Views/Students/Lists.cshtml
@model IEnumerable<StudentsCRUDWithImageMVC.Models.ListsModel>

@{
    ViewBag.Title = "Lists";
}

<h2 style="color:darkblue" align="center">Students Details</h2>
<p>
    @Html.ActionLink("Create New", "Insert", null, new { @class = "btn btn-primary" })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RollNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fees)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JoiningDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.RollNo</td>
            <td>@item.Name</td>
            <td>@item.City</td>
            <td>@item.State</td>
            <td>@item.Fees</td>
            <td>@item.JoiningDate.ToShortDateString()</td>
            <td>
                @if (item.Image != null)
                {
                    string imageBase64 = Convert.ToBase64String(item.Image);
                    string imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                    <img src="@imageSrc" width="100" height="60" />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RollNo }) |
                @Html.ActionLink("Details", "Details", new { id = item.RollNo }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RollNo })
            </td>
        </tr>
    }
</table>

Views/Students/SentItems.cshtml
@model List<StudentsCRUDWithImageMVC.Models.MessageModel>

<h2>Sent Items</h2>

<table>
    <thead>
        <tr>
            <th>To</th>
            <th>Subject</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var msg in Model)
        {
            <tr>
                <td>@msg.ReceiverEmail</td>
                <td>@msg.Subject</td>
                <td>@msg.SentDate.ToString("g")</td>
            </tr>
        }
    </tbody>
</table>